# ================= ПЕРЕМЕННЫЕ =================
x-variables:
  backup_sub: &backup_sub "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/Vless-Reality-White-Lists-Rus-Mobile.txt"
  whitelist_url: &whitelist_url "https://raw.githubusercontent.com/Oradep/CopperProxy/refs/heads/main/whitelist_mihomo.yaml"

# ================= УДОБСТВО (UX) =================
profile:
  store-selected: true
  store-fake-ip: true

# ================= ОСНОВНЫЕ НАСТРОЙКИ =================
port: 7890
allow-lan: false
mode: rule
log-level: info
ipv6: false
udp: true

tun:
  enable: true
  stack: mixed
  dns-hijack: ["any:53"]
  auto-route: true

dns:
  enable: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 8.8.8.8
    - 1.1.1.1
  nameserver-policy:
    "+.ru": "77.88.8.8"
    "+.рф": "77.88.8.8"

# ================= ПРОВАЙДЕРЫ =================
proxy-providers:
  public-backup-subs:
    type: http
    url: *backup_sub
    interval: 3600
    health-check:
      enable: true
      url: "http://connectivitycheck.gstatic.com/generate_204"
      expected-status: 204
      interval: 120

# ================= ГРУППЫ =================
proxy-groups:
  - name: "🚀 CopperProxy (Авто)"
    type: url-test
    icon: "https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/rocket.svg"
    use:
      - public-backup-subs
    url: "http://connectivitycheck.gstatic.com/generate_204"
    expected-status: 204
    interval: 60
    tolerance: 100

# ================= СПИСКИ (БЕЛЫЙ) =================
rule-providers:
  personal-whitelist:
    type: http
    behavior: classical
    format: yaml   
    url: *whitelist_url
    interval: 86400 

# ================= МАРШРУТИЗАЦИЯ =================
rules:
  - GEOIP,lan,DIRECT,no-resolve
  - GEOSITE,private,DIRECT

  # 1. РУ-Сайты (Из вашего файла) -> НАПРЯМУЮ
  - RULE-SET,personal-whitelist,DIRECT

  # 2. ВСЁ ОСТАЛЬНОЕ В МИРЕ -> В COPPER PROXY
  - MATCH,🚀 CopperProxy (Авто)